// ========================
// AI Tools Database
// ========================

export const CATEGORIES = [
  { id: 'all', label: 'All Tools', emoji: '🌌', color: '#a855f7' },
  { id: 'chat', label: 'Chat & Research', emoji: '💬', color: '#6366f1' },
  { id: 'code', label: 'Code & Dev', emoji: '💻', color: '#10b981' },
  { id: 'image', label: 'Image Generation', emoji: '🎨', color: '#f59e0b' },
  { id: 'video', label: 'Video Generation', emoji: '🎬', color: '#ef4444' },
  { id: 'voice', label: 'Voice & Speech', emoji: '🎙️', color: '#a855f7' },
  { id: 'api', label: 'API & Cloud', emoji: '🔑', color: '#14b8a6' },
  { id: 'web', label: 'Website Builders', emoji: '🌐', color: '#ec4899' },
  { id: 'search', label: 'AI Search', emoji: '🔍', color: '#3b82f6' },
  { id: 'productivity', label: 'Productivity', emoji: '⚡', color: '#8b5cf6' },
]

export const AI_TOOLS = [
  // ---- CHAT & RESEARCH ----
  {
    id: '1', slug: 'chatgpt',
    name: 'ChatGPT', company: 'OpenAI',
    category: 'chat', emoji: '🤖',
    color: '#10a37f',
    description: 'The world\'s most popular AI chatbot for conversation, research, writing, analysis, and coding assistance.',
    longDescription: 'ChatGPT by OpenAI is one of the most versatile and widely used AI models. It supports writing, coding, research, summarization, math, and much more. GPT-4o brings multimodal capabilities.',
    website: 'https://chat.openai.com',
    pricing: {
      free: 'GPT-3.5 limited usage',
      pro: '$20/month (GPT-4o access)',
      api: 'From $0.150/1M input tokens (GPT-4o-mini)',
    },
    features: ['Multimodal (text + image)', 'Code generation', 'Research', 'Plugins/GPTs', 'Voice mode'],
    useCases: ['Customer support', 'Content writing', 'Code review', 'Data analysis'],
    rating: 4.8, users: '200M+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '2', slug: 'gemini',
    name: 'Gemini', company: 'Google',
    category: 'chat', emoji: '✨',
    color: '#4285f4',
    description: 'Google\'s most capable AI model with deep Google integration, multimodal understanding, and Workspace connectivity.',
    longDescription: 'Gemini by Google is a multimodal AI that can understand text, images, audio, video, and code. Deeply integrated with Google Workspace, Search, and developer tools.',
    website: 'https://gemini.google.com',
    pricing: {
      free: 'Gemini 1.5 Flash limited',
      pro: '$19.99/month (Gemini Advanced)',
      api: 'From $0.075/1M tokens (Flash)',
    },
    features: ['Multimodal', 'Google integration', 'Real-time search', 'Long context (1M tokens)', 'Code execution'],
    useCases: ['Research', 'Document analysis', 'Google Workspace', 'Developer tools'],
    rating: 4.7, users: '100M+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '3', slug: 'claude',
    name: 'Claude', company: 'Anthropic',
    category: 'chat', emoji: '🧠',
    color: '#cc785c',
    description: 'Anthropic\'s safety-focused AI with exceptional reasoning, writing quality, and 200K context window.',
    longDescription: 'Claude 3.5 by Anthropic excels at nuanced reasoning, long documents analysis, and produces some of the highest-quality written outputs of any AI model.',
    website: 'https://claude.ai',
    pricing: {
      free: 'Limited daily messages',
      pro: '$20/month',
      api: 'From $0.25/1M input tokens (Haiku)',
    },
    features: ['200K context window', 'Safety-focused', 'Superior writing quality', 'Code & analysis', 'Document understanding'],
    useCases: ['Legal documents', 'Research papers', 'Complex coding', 'Creative writing'],
    rating: 4.9, users: '20M+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '4', slug: 'copilot',
    name: 'Copilot', company: 'Microsoft',
    category: 'chat', emoji: '🪁',
    color: '#0078d4',
    description: 'Microsoft\'s AI powered by GPT-4 with Bing web search, integrated into Windows and Microsoft 365.',
    longDescription: 'Microsoft Copilot brings GPT-4 with real-time Bing search results into Windows, Microsoft 365 apps, and the web browser for productivity-focused tasks.',
    website: 'https://copilot.microsoft.com',
    pricing: {
      free: 'Free with Microsoft account',
      pro: '$20/month (Copilot Pro)',
      api: 'Via Azure OpenAI Service',
    },
    features: ['Bing web search', 'Microsoft 365 integration', 'Image generation (DALL-E)', 'Voice & vision', 'Enterprise security'],
    useCases: ['Office productivity', 'Research', 'Image creation', 'Windows integration'],
    rating: 4.5, users: '50M+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '5', slug: 'grok',
    name: 'Grok', company: 'xAI',
    category: 'chat', emoji: '⚡',
    color: '#e7e7e7',
    description: 'xAI\'s witty AI with real-time X (Twitter) data access, unfiltered responses, and DeepSearch capabilities.',
    website: 'https://x.ai',
    pricing: {
      free: 'Limited on X platform',
      pro: '$8/month (X Premium)',
      api: 'From $5/1M input tokens',
    },
    features: ['Real-time X data', 'DeepSearch', 'Image generation', 'Uncensored mode', 'Voice'],
    useCases: ['News analysis', 'Social media', 'Trending topics', 'Research'],
    rating: 4.4, users: '10M+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '6', slug: 'perplexity',
    name: 'Perplexity AI', company: 'Perplexity',
    category: 'search', emoji: '🔍',
    color: '#20b2aa',
    description: 'AI-powered search engine that provides cited, real-time answers from trusted web sources.',
    website: 'https://perplexity.ai',
    pricing: {
      free: 'Free plan available',
      pro: '$20/month',
      api: 'From $0.2/1M tokens',
    },
    features: ['Real-time web search', 'Source citations', 'Pro search modes', 'File analysis', 'API access'],
    useCases: ['Research', 'Fact-checking', 'Academic work', 'News'],
    rating: 4.6, users: '15M+',
    apiAvailable: true,
    trending: false,
  },
  {
    id: '7', slug: 'meta-llama',
    name: 'Meta Llama', company: 'Meta',
    category: 'chat', emoji: '🦙',
    color: '#0866ff',
    description: 'Meta\'s open-source large language model available for free download and deployment.',
    website: 'https://llama.meta.com',
    pricing: {
      free: 'Open source (self-hosted)',
      pro: 'Pay per token on cloud providers',
      api: 'Free on Groq/Together AI',
    },
    features: ['Open source', 'Self-hostable', 'Multiple sizes (7B–405B)', 'Fine-tuning support', 'Commercial use'],
    useCases: ['Custom AI applications', 'Research', 'Enterprise deployment'],
    rating: 4.5, users: '5M+ developers',
    apiAvailable: true,
    trending: false,
  },

  // ---- CODE & DEV ----
  {
    id: '8', slug: 'cursor',
    name: 'Cursor', company: 'Anysphere',
    category: 'code', emoji: '🖱️',
    color: '#7c3aed',
    description: 'AI-native code editor built on VSCode with context-aware completions, chat, and autonomous coding agent.',
    website: 'https://cursor.sh',
    pricing: {
      free: '2 weeks trial',
      pro: '$20/month',
      api: 'N/A (bundled)',
    },
    features: ['Full codebase context', 'AI chat sidebar', 'Composer agent', 'VSCode compatible', 'Multi-file edits'],
    useCases: ['Software development', 'Code refactoring', 'Bug fixing', 'Full-stack projects'],
    rating: 4.8, users: '2M+ devs',
    apiAvailable: false,
    trending: true,
  },
  {
    id: '9', slug: 'github-copilot',
    name: 'GitHub Copilot', company: 'GitHub / Microsoft',
    category: 'code', emoji: '🐙',
    color: '#24292e',
    description: 'AI pair programmer for VS Code, JetBrains, and GitHub. Suggests code completions and full functions.',
    website: 'https://github.com/features/copilot',
    pricing: {
      free: 'Free for students/OSS',
      pro: '$10/month',
      api: 'N/A',
    },
    features: ['IDE integration', 'Chat assistant', 'Code suggestions', 'Multi-language', 'PR summaries'],
    useCases: ['Code completion', 'Bug fixes', 'Documentation', 'Test generation'],
    rating: 4.6, users: '10M+ devs',
    apiAvailable: false,
    trending: false,
  },
  {
    id: '10', slug: 'antigravity',
    name: 'Antigravity', company: 'Google DeepMind',
    category: 'code', emoji: '🚀',
    color: '#4285f4',
    description: 'Google DeepMind\'s advanced AI coding assistant with deep codebase understanding and agentic capabilities.',
    website: 'https://antigravity.dev',
    pricing: {
      free: 'Available via IDE',
      pro: 'Subscription based',
      api: 'N/A',
    },
    features: ['Agentic coding', 'Full codebase context', 'Deep refactoring', 'Multi-step planning', 'Task management'],
    useCases: ['Large-scale refactoring', 'Feature implementation', 'Bug hunting', 'Architecture planning'],
    rating: 4.9, users: '1M+ devs',
    apiAvailable: false,
    trending: true,
  },
  {
    id: '11', slug: 'replit',
    name: 'Replit', company: 'Replit',
    category: 'web', emoji: '🔄',
    color: '#f26207',
    description: 'Browser-based IDE with AI coding assistance, deployment, and collaborative coding for any language.',
    website: 'https://replit.com',
    pricing: {
      free: 'Free tier available',
      pro: '$25/month (Replit Core)',
      api: 'N/A',
    },
    features: ['Browser-based IDE', 'AI agent (Replit Agent)', 'Instant deployment', '50+ languages', 'Collaboration'],
    useCases: ['Rapid prototyping', 'Learning', 'Full-stack apps', 'Hackathons'],
    rating: 4.5, users: '30M+',
    apiAvailable: false,
    trending: false,
  },

  // ---- WEBSITE BUILDERS ----
  {
    id: '12', slug: 'lovable',
    name: 'Lovable', company: 'Lovable Technologies',
    category: 'web', emoji: '💜',
    color: '#7c3aed',
    description: 'AI full-stack web app builder. Describe your app in natural language and get production-ready React + Supabase code.',
    website: 'https://lovable.dev',
    pricing: {
      free: '5 messages/day',
      pro: '$20/month (100 messages)',
      api: 'N/A',
    },
    features: ['Natural language to app', 'React + Supabase', 'GitHub integration', 'Custom domains', 'Visual editor'],
    useCases: ['SaaS apps', 'Prototypes', 'Internal tools', 'MVPs'],
    rating: 4.7, users: '500K+',
    apiAvailable: false,
    trending: true,
  },
  {
    id: '13', slug: 'bolt',
    name: 'Bolt.new', company: 'StackBlitz',
    category: 'web', emoji: '⚡',
    color: '#f59e0b',
    description: 'AI-powered full-stack web development in the browser with instant preview and one-click deployment.',
    website: 'https://bolt.new',
    pricing: {
      free: 'Free tier (limited tokens)',
      pro: '$20/month',
      api: 'N/A',
    },
    features: ['In-browser full-stack', 'npm package support', 'Instant preview', 'Netlify deployment', 'Code editing'],
    useCases: ['Quick prototypes', 'Landing pages', 'React/Next.js apps', 'Learning'],
    rating: 4.6, users: '2M+',
    apiAvailable: false,
    trending: true,
  },
  {
    id: '14', slug: 'v0',
    name: 'v0.dev', company: 'Vercel',
    category: 'web', emoji: '▲',
    color: '#000000',
    description: 'Vercel\'s AI UI generator. Describe UI and get production-ready shadcn/ui + Tailwind React components.',
    website: 'https://v0.dev',
    pricing: {
      free: '200 credits/month',
      pro: '$20/month',
      api: 'N/A',
    },
    features: ['UI generation', 'shadcn/ui components', 'Tailwind CSS', 'Next.js ready', 'Iterative design'],
    useCases: ['UI prototyping', 'Component building', 'Design systems', 'Dashboards'],
    rating: 4.6, users: '1M+',
    apiAvailable: false,
    trending: true,
  },
  {
    id: '15', slug: 'base44',
    name: 'Base44', company: 'Base44',
    category: 'web', emoji: '🏗️',
    color: '#6366f1',
    description: 'AI-powered no-code app builder for creating internal tools, forms, databases, and business apps fast.',
    website: 'https://base44.com',
    pricing: {
      free: 'Free plan',
      pro: '$29/month',
      api: 'N/A',
    },
    features: ['No-code builder', 'Database integration', 'Forms & workflows', 'Team collaboration', 'Custom logic'],
    useCases: ['Internal tools', 'CRM', 'Inventory management', 'Business workflows'],
    rating: 4.4, users: '200K+',
    apiAvailable: false,
    trending: false,
  },
  {
    id: '16', slug: 'emergent',
    name: 'Emergent', company: 'Emergent',
    category: 'web', emoji: '🌱',
    color: '#059669',
    description: 'AI agent that builds full-stack web applications from a single prompt with autonomous planning and execution.',
    website: 'https://emergent.sh',
    pricing: {
      free: 'Limited credits',
      pro: '$30/month',
      api: 'N/A',
    },
    features: ['Autonomous agent', 'Full-stack apps', 'Database design', 'API creation', 'Multi-step projects'],
    useCases: ['MVPs', 'Business tools', 'Complex web apps'],
    rating: 4.3, users: '100K+',
    apiAvailable: false,
    trending: false,
  },

  // ---- IMAGE GENERATION ----
  {
    id: '17', slug: 'dall-e',
    name: 'DALL·E 3', company: 'OpenAI',
    category: 'image', emoji: '🎨',
    color: '#10a37f',
    description: 'OpenAI\'s state-of-the-art image generator with natural language understanding and photorealistic output.',
    website: 'https://openai.com/dall-e-3',
    pricing: {
      free: 'Via ChatGPT free',
      pro: 'Via ChatGPT Plus',
      api: '$0.040/image (1024×1024 standard)',
    },
    features: ['Photorealistic images', 'Prompt following', 'Inpainting', 'Natural language', 'Style control'],
    useCases: ['Marketing materials', 'Art creation', 'Product mockups', 'Social media'],
    rating: 4.7, users: '50M+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '18', slug: 'midjourney',
    name: 'Midjourney', company: 'Midjourney',
    category: 'image', emoji: '🖼️',
    color: '#ff6b6b',
    description: 'Premium AI art generator known for stunning, artistic, and highly detailed image outputs via Discord.',
    website: 'https://midjourney.com',
    pricing: {
      free: 'No free tier',
      pro: '$10/month (basic)',
      api: 'Not publicly available',
    },
    features: ['Artistic quality', 'Style control', 'Upscaling', 'Variations', 'Discord bot'],
    useCases: ['Digital art', 'Concept art', 'Illustrations', 'Brand imagery'],
    rating: 4.8, users: '20M+',
    apiAvailable: false,
    trending: true,
  },
  {
    id: '19', slug: 'stable-diffusion',
    name: 'Stable Diffusion', company: 'Stability AI',
    category: 'image', emoji: '🌊',
    color: '#7c3aed',
    description: 'Open-source image generation model that can be self-hosted, fine-tuned, and run locally for free.',
    website: 'https://stability.ai',
    pricing: {
      free: 'Free (self-hosted)',
      pro: '$20/month (DreamStudio)',
      api: 'From $0.004/image',
    },
    features: ['Open source', 'Self-hostable', 'LoRA fine-tuning', 'ControlNet', 'Unlimited generation'],
    useCases: ['Custom AI art', 'Product design', 'Game assets', 'Research'],
    rating: 4.5, users: '10M+ developers',
    apiAvailable: true,
    trending: false,
  },
  {
    id: '20', slug: 'ideogram',
    name: 'Ideogram AI', company: 'Ideogram',
    category: 'image', emoji: '💡',
    color: '#06b6d4',
    description: 'AI image generator excelling at text rendering within images – perfect for logos, posters, and graphics.',
    website: 'https://ideogram.ai',
    pricing: {
      free: '25 slow generations/day',
      pro: '$8/month',
      api: 'From $0.08/image',
    },
    features: ['Text in images', 'Logo creation', 'Style variety', 'High resolution', 'Realism & illustration'],
    useCases: ['Logos', 'Posters', 'Typography art', 'Marketing'],
    rating: 4.6, users: '5M+',
    apiAvailable: true,
    trending: false,
  },

  // ---- VIDEO GENERATION ----
  {
    id: '21', slug: 'gemini-veo',
    name: 'Veo 3', company: 'Google DeepMind',
    category: 'video', emoji: '🎬',
    color: '#4285f4',
    description: 'Google\'s most advanced video generation model that creates high-quality, cinematic video with audio from text.',
    website: 'https://deepmind.google/technologies/veo',
    pricing: {
      free: 'Limited via Google AI Studio',
      pro: 'Via Vertex AI',
      api: 'Contact Google for pricing',
    },
    features: ['Cinematic video', 'Audio generation', '4K resolution', 'Motion control', 'Style presets'],
    useCases: ['Content creation', 'Advertising', 'Film production', 'Education'],
    rating: 4.8, users: '1M+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '22', slug: 'sora',
    name: 'Sora', company: 'OpenAI',
    category: 'video', emoji: '🎥',
    color: '#10a37f',
    description: 'OpenAI\'s video generation model that creates realistic, imaginative scenes from text and images.',
    website: 'https://sora.com',
    pricing: {
      free: 'Limited via ChatGPT Plus',
      pro: '$200/month (usage-based)',
      api: 'In beta',
    },
    features: ['Text-to-video', 'Image-to-video', 'Up to 1 minute', 'Multiple aspect ratios', 'Character consistency'],
    useCases: ['Short films', 'Ads', 'Social content', 'Prototyping'],
    rating: 4.7, users: '500K+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '23', slug: 'runway-ml',
    name: 'Runway Gen-4', company: 'Runway',
    category: 'video', emoji: '✈️',
    color: '#ff6b6b',
    description: 'Professional AI video generation with advanced motion brush, style transfer, and video editing tools.',
    website: 'https://runwayml.com',
    pricing: {
      free: '125 credits one-time',
      pro: '$15/month (625 credits)',
      api: 'From $0.05/second',
    },
    features: ['Gen-4 video', 'Motion brush', 'Style transfer', 'Inpainting', 'Super-slow motion'],
    useCases: ['Professional video', 'VFX', 'Music videos', 'Social media'],
    rating: 4.6, users: '3M+',
    apiAvailable: true,
    trending: false,
  },

  // ---- VOICE & SPEECH ----
  {
    id: '24', slug: 'google-tts',
    name: 'Google Text-to-Speech', company: 'Google Cloud',
    category: 'voice', emoji: '🔊',
    color: '#4285f4',
    description: 'Google Cloud\'s TTS API with 380+ voices across 50+ languages including Studio-quality voice models.',
    website: 'https://cloud.google.com/text-to-speech',
    pricing: {
      free: '4M characters/month free',
      pro: 'N/A',
      api: '$4.00/1M characters (Standard), $16.00/1M (WaveNet), $160/1M (Studio)',
    },
    features: ['380+ voices', '50+ languages', 'SSML support', 'Neural/WaveNet voices', 'Studio quality'],
    useCases: ['Apps', 'Accessibility', 'IVR systems', 'Audiobooks', 'E-learning'],
    rating: 4.7, users: '500K+ apps',
    apiAvailable: true,
    trending: false,
  },
  {
    id: '25', slug: 'elevenlabs',
    name: 'ElevenLabs', company: 'ElevenLabs',
    category: 'voice', emoji: '🎙️',
    color: '#f59e0b',
    description: 'Hyper-realistic AI voice synthesis, voice cloning, and multilingual text-to-speech with emotional control.',
    website: 'https://elevenlabs.io',
    pricing: {
      free: '10K chars/month',
      pro: '$5/month (30K chars)',
      api: 'From $5/month',
    },
    features: ['Voice cloning', '29 languages', 'Emotion control', 'Real-time voice', 'Audiobook creation'],
    useCases: ['Podcasts', 'Characters', 'Audiobooks', 'Customer service', 'Games'],
    rating: 4.9, users: '2M+',
    apiAvailable: true,
    trending: true,
  },
  {
    id: '26', slug: 'whisper',
    name: 'Whisper (OpenAI)', company: 'OpenAI',
    category: 'voice', emoji: '🎤',
    color: '#10a37f',
    description: 'OpenAI\'s open-source speech-to-text model with robust multilingual transcription and translation.',
    website: 'https://openai.com/research/whisper',
    pricing: {
      free: 'Free (self-hosted)',
      pro: 'N/A',
      api: '$0.006/minute',
    },
    features: ['Multi-language STT', 'Translation to English', 'Open source', 'Robust accuracy', 'Multiple sizes'],
    useCases: ['Transcription', 'Subtitles', 'Voice commands', 'Meeting notes'],
    rating: 4.8, users: '5M+ developers',
    apiAvailable: true,
    trending: false,
  },
  {
    id: '27', slug: 'dialogflow',
    name: 'Dialogflow CX', company: 'Google Cloud',
    category: 'api', emoji: '💬',
    color: '#4285f4',
    description: 'Google Cloud\'s enterprise conversational AI platform for building advanced chatbots and voice agents.',
    website: 'https://cloud.google.com/dialogflow',
    pricing: {
      free: '1st 1B text chars/month free',
      pro: 'N/A',
      api: '$0.007/request (CX text), $0.06/min (voice)',
    },
    features: ['Visual flow builder', 'Multi-turn conversations', 'Omnichannel', 'NLP understanding', 'Analytics'],
    useCases: ['Customer service bots', 'IVR', 'Virtual assistants', 'Enterprise chatbots'],
    rating: 4.5, users: '100K+ enterprises',
    apiAvailable: true,
    trending: false,
  },

  // ---- API & CLOUD ----
  {
    id: '28', slug: 'aws-bedrock',
    name: 'AWS Bedrock', company: 'Amazon',
    category: 'api', emoji: '☁️',
    color: '#ff9900',
    description: 'AWS managed service providing access to top AI models (Claude, Llama, Titan, Mistral, Stable Diffusion) via API.',
    website: 'https://aws.amazon.com/bedrock',
    pricing: {
      free: 'Pay per token / image',
      pro: 'N/A',
      api: 'Varies by model (from ~$0.25/1M tokens)',
    },
    features: ['Multiple models', 'Fine-tuning', 'RAG support', 'Agents', 'Enterprise security'],
    useCases: ['Enterprise AI', 'RAG applications', 'Fine-tuned models', 'Production AI'],
    rating: 4.6, users: '50K+ enterprises',
    apiAvailable: true,
    trending: false,
  },
  {
    id: '29', slug: 'azure-openai',
    name: 'Azure OpenAI', company: 'Microsoft',
    category: 'api', emoji: '🔷',
    color: '#0078d4',
    description: 'Enterprise-grade OpenAI models hosted on Azure with compliance, security, and regional data residency.',
    website: 'https://azure.microsoft.com/en-us/products/ai-services/openai-service',
    pricing: {
      free: 'Pay per token',
      pro: 'N/A',
      api: 'Same as OpenAI + Azure infrastructure',
    },
    features: ['GPT-4o access', 'Enterprise compliance', 'VNet integration', 'Regional deployment', 'RBAC'],
    useCases: ['Enterprise apps', 'Healthcare AI', 'Government', 'Financial services'],
    rating: 4.7, users: '30K+ enterprises',
    apiAvailable: true,
    trending: false,
  },
  {
    id: '30', slug: 'hugging-face',
    name: 'Hugging Face', company: 'Hugging Face',
    category: 'api', emoji: '🤗',
    color: '#ffcc00',
    description: 'The AI community platform with 500K+ models, datasets, and serverless inference APIs for any ML task.',
    website: 'https://huggingface.co',
    pricing: {
      free: 'Serverless inference (limited)',
      pro: '$9/month',
      api: 'From $0.0001/request',
    },
    features: ['500K+ models', 'Serverless inference', 'Model training', 'Datasets', 'Spaces (demos)'],
    useCases: ['Research', 'Production AI', 'Fine-tuning', 'Prototype demos'],
    rating: 4.8, users: '10M+ developers',
    apiAvailable: true,
    trending: false,
  },
  {
    id: '31', slug: 'vertex-ai',
    name: 'Vertex AI', company: 'Google Cloud',
    category: 'api', emoji: '🟢',
    color: '#34a853',
    description: 'Google Cloud\'s unified ML platform with Gemini, AutoML, custom training, and model deployment at scale.',
    website: 'https://cloud.google.com/vertex-ai',
    pricing: {
      free: '$300 free credits for new users',
      pro: 'N/A',
      api: 'From $0.25/1M tokens (Gemini Pro)',
    },
    features: ['Gemini access', 'AutoML', 'MLOps', 'Custom training', 'Feature store'],
    useCases: ['Enterprise ML', 'Production models', 'MLOps pipelines', 'RAG systems'],
    rating: 4.6, users: '40K+ enterprises',
    apiAvailable: true,
    trending: false,
  },
  {
    id: '32', slug: 'groq',
    name: 'Groq', company: 'Groq',
    category: 'api', emoji: '⚡',
    color: '#f97316',
    description: 'Ultra-fast LLM inference API running Llama, Mixtral, and other models at speeds of 500+ tokens/second.',
    website: 'https://groq.com',
    pricing: {
      free: 'Free tier (rate-limited)',
      pro: 'N/A',
      api: 'From $0.05/1M tokens (Llama 3 8B)',
    },
    features: ['500+ tok/sec speed', 'Llama, Mixtral models', 'JSON mode', 'Tool use', 'Low latency'],
    useCases: ['Real-time AI apps', 'Chatbots', 'Low-latency inference'],
    rating: 4.7, users: '500K+ developers',
    apiAvailable: true,
    trending: true,
  },
]

// ========================
// API Key Guide Data
// ========================
export const API_KEY_GUIDES = {
  'google-tts': {
    name: 'Google Cloud Text-to-Speech',
    steps: [
      { title: 'Create Google Cloud Account', desc: 'Go to console.cloud.google.com and create an account or sign in.' },
      { title: 'Create a New Project', desc: 'Click "New Project", give it a name, and click Create.' },
      { title: 'Enable Text-to-Speech API', desc: 'Go to APIs & Services > Library, search "Text-to-Speech API" and click Enable.' },
      { title: 'Create Credentials', desc: 'Go to APIs & Services > Credentials > Create Credentials > API Key.' },
      { title: 'Copy & Secure API Key', desc: 'Copy your API key. Restrict it to Text-to-Speech API for security.' },
    ],
    docsUrl: 'https://cloud.google.com/text-to-speech/docs',
  },
  'openai': {
    name: 'OpenAI API',
    steps: [
      { title: 'Create OpenAI Account', desc: 'Go to platform.openai.com and sign up.' },
      { title: 'Verify Your Email', desc: 'Confirm your email address.' },
      { title: 'Go to API Keys', desc: 'Navigate to Settings > API Keys.' },
      { title: 'Create New Secret Key', desc: 'Click "Create new secret key", name it, and copy it immediately.' },
      { title: 'Set Up Billing', desc: 'Add a payment method in Settings > Billing to use the API.' },
    ],
    docsUrl: 'https://platform.openai.com/docs',
  },
}

export const NAV_LINKS = [
  { label: 'Features', path: '/tools', hasDropdown: true },
  { label: 'Solutions', path: '/categories' },
  { label: 'Plans', path: '/compare' },
  { label: 'Learning', path: '/api-key-guide', hasDropdown: true },
]

export const MARQUEE_TOOLS = [
  { name: 'ChatGPT', emoji: '🤖', color: '#10a37f' },
  { name: 'Gemini', emoji: '✨', color: '#4285f4' },
  { name: 'Claude', emoji: '🧠', color: '#cc785c' },
  { name: 'Copilot', emoji: '🪁', color: '#0078d4' },
  { name: 'Grok', emoji: '⚡', color: '#e7e7e7' },
  { name: 'Replit', emoji: '🔄', color: '#f26207' },
  { name: 'Cursor', emoji: '🖱️', color: '#7c3aed' },
  { name: 'Midjourney', emoji: '🖼️', color: '#ff6b6b' },
  { name: 'ElevenLabs', emoji: '🎙️', color: '#f59e0b' },
  { name: 'Runway', emoji: '✈️', color: '#ff6b6b' },
  { name: 'Lovable', emoji: '💜', color: '#7c3aed' },
  { name: 'Bolt.new', emoji: '⚡', color: '#f59e0b' },
]
